/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multimedia_Processing_System;

import cpit380practice.FileChooser;
import cpit380practice.SoundSample;
import javax.swing.JOptionPane;

/**
 *
 * @author WinDows
 */
public class Sound extends javax.swing.JFrame {

    /**
     * Creates new form Sound
     */
    public Sound() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private cpit380practice.Sound currentSound;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        blendingSound2 = new javax.swing.JLabel();
        reversingSound2 = new javax.swing.JLabel();
        clipSound2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/photo_2020-12-06_11-02-19.jpg"))); // NOI18N

        blendingSound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blendingSound2MouseClicked(evt);
            }
        });

        reversingSound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reversingSound2MouseClicked(evt);
            }
        });

        clipSound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clipSound2MouseClicked(evt);
            }
        });

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(blendingSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(reversingSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(clipSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blendingSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(reversingSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(clipSound2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blendingSound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blendingSound2MouseClicked
        // TODO add your handling code here:
        cpit380practice.Sound target = new cpit380practice.Sound("C:\\Users\\WinDows\\Desktop\\sounds(2)\\sec3silence.wav");

            String filePath1 = FileChooser.pickAFile();
            cpit380practice.Sound sound1 = new cpit380practice.Sound(filePath1);

            for (int i = 0; i < currentSound.getLength() - 1; i++) {

                target.setSampleValueAt(i, currentSound.getSampleValueAt(i) + sound1.getSampleValueAt(i));

            }
        target.play();
    }//GEN-LAST:event_blendingSound2MouseClicked

    private void reversingSound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reversingSound2MouseClicked
        // TODO add your handling code here:
        SoundSample[] sound = currentSound.getSamples();
        int index = 0;

        cpit380practice.Sound target = new cpit380practice.Sound("C:\\Users\\WinDows\\Desktop\\sounds(2)\\sec3silence.wav");

        for (int i = currentSound.getLength() - 1; i >= 0; i--) {

            SoundSample temp = sound[i];
            sound[index] = temp;

            target.setSampleValueAt(index, currentSound.getSampleValueAt(i));
            index++;
        }

        target.play();
    }//GEN-LAST:event_reversingSound2MouseClicked

    private void clipSound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clipSound2MouseClicked
        // TODO add your handling code here:
        int length = currentSound.getLength();
        String first = JOptionPane.showInputDialog(null, "Number of index is " + length + " \nEnter the start Index: ");
        String last = JOptionPane.showInputDialog(null, "Number of index is " + length + " \nEnter the end Index: ");
        int firstIndx = Integer.parseInt(first);
        int lastIndx = Integer.parseInt(last);

        cpit380practice.Sound s = currentSound.clip(firstIndx, lastIndx);
        s.play();
    }//GEN-LAST:event_clipSound2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
             try {
            String filePath = FileChooser.pickAFile();
            currentSound = new cpit380practice.Sound(filePath);
//            changeContentStatus(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Some error happend:" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         currentSound.play();
    }//GEN-LAST:event_jLabel3MouseClicked

//    private void changeContentStatus(boolean status) {
//        clipSound2.setEnabled(status);
//        reversingSound2.setEnabled(status);
//        blendingSound2.setEnabled(status);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blendingSound2;
    private javax.swing.JLabel clipSound2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel reversingSound2;
    // End of variables declaration//GEN-END:variables
}
